// window.API_HOST = 'http://localhost:4000'
// window.GTM_ID = ''
// window.BASE_URL = 'example.com'
// window.STREETS_TILE_LAYER_URL = 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
// window.LOGO_URL = 'https://placekitten.com/530/530'
// window.MAPBOX_ACCESS_TOKEN = ''
// window.AUTH0_DOMAIN = 'smartcolumbusos-demo.auth0.com'
// window.AUTH0_CLIENT_ID = 'sfe5fZzFXsv5gIRXz8V3zkR7iaZBMvL0'
// window.AUTH0_AUDIENCE = 'discovery_api'
window.API_HOST = 'https://data.dev.internal.smartcolumbusos.com'
window.GTM_ID = 'GTM-MQV8L2F'
window.BASE_URL = 'dev-smartos.com'
window.STREETS_TILE_LAYER_URL = 'https://{s}.tiles.mapbox.com/styles/v1/mapbox/streets-v10/tiles/{z}/{x}/{y}{r}?access_token=pk.eyJ1Ijoic21ydGNidXMiLCJhIjoiY2ptMTB6YjIzMGVuazNwcWcyczk3a2ZmNSJ9.SjVhquTC7K5RzbGqoGZUYg'
window.MAPBOX_ACCESS_TOKEN = 'pk.eyJ1Ijoic21ydGNidXMiLCJhIjoiY2ptMTB6YjIzMGVuazNwcWcyczk3a2ZmNSJ9.SjVhquTC7K5RzbGqoGZUYg'
window.LOGO_URL = 'https://placekitten.com/530/530'
window.AUTH0_DOMAIN = 'smartcolumbusos-dev.auth0.com'
window.AUTH0_CLIENT_ID = 'PIT5nBsWTyIWbD7lhIUzeud7LS10q9W4'
window.AUTH0_AUDIENCE = 'discovery_api'
