window.API_HOST = 'http://localhost:4000'
window.GTM_ID = ''
window.BASE_URL = 'example.com'
window.STREETS_TILE_LAYER_URL = 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
window.LOGO_URL = 'https://placekitten.com/530/530'
